### ISSUE TITLE
Sysdig throws execption when using evt.rawarg.path for string comparisons

### ISSUE THREAD

**Issue by HybridReaverHD** [falcosecurity/libs#112]
**Describe the bug**

when using evt.rawarg.path and comparing with a string (startswith, contains) an error is thrown stating:
"wrong parameter type 17"

This originates from [value_parser.cpp](https://github.com/falcosecurity/libs/blob/b9d2fccebf0feb94729c78bee0368c70d9c24819/userspace/libsinsp/value_parser.cpp#L28) string_to_rawarg function where handling for PT_FSPATH is missing
adding "case PT_FSPATH:" to [line 111](https://github.com/falcosecurity/libs/blob/b9d2fccebf0feb94729c78bee0368c70d9c24819/userspace/libsinsp/value_parser.cpp#L111) in that file (the case for normal strings) might be the trick

**How to reproduce it**

from shell:
sysdig "evt.type=mkdir and evt.rawarg.path startswith 'foo'" -p "%evt.arg.path %evt.rawarg.path"

**Expected behavior**
not exiting with an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/36007801/139260267-05abd2af-07bf-4ae7-ae5f-71de0f9ef2c7.png)

- OS: CENTOS 7
- Kernel: 3.10
- Installation method: yum

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! I will look into it asap ;)

**Comment by FedeDP** [comment]
The issue should be solved by https://github.com/falcosecurity/libs/pull/116 ;)
