### ISSUE TITLE
"libdriver-event-schema.so" should be renamed to make it clear what it's for

### ISSUE THREAD

**Issue by dkogan** [falcosecurity/libs#1202]
Hello. I'm the Debian maintainer. I just pushed a new package, and I have a suggestion. All the other `libscap` libraries are called `libscap-....`. A user seeing this file in `/usr/lib/ARCHITECTURE/` is more or less clear on what this file is (it'd be better if these files were called `libfalco-scap-...` or something, but this is close-enough. The `libdriver-event-schema.so` file is different from all the others, and have a very generic name. Can we please rename it to `libscap-whatever`?

Thanks.

**Comment by FedeDP** [comment]
Hi!
Thanks for opening this request!

> (it'd be better if these files were called libfalco-scap-...

Well, Falco is not the only consumer of these libraries, therefore we actually used the library real name.

> The libdriver-event-schema.so file is different from all the others, and have a very generic name.

I'll ask @gnosek that is doing a big refactor around that code.
Do we even need this lib nowadays?

Thank you very much!

**Comment by dkogan** [comment]
> Well, Falco is not the only consumer of these libraries, therefore we
> actually used the library real name.

OK, that's reasonable. But "driver-event-schema" is too generic. Driver
for what?

**Comment by gnosek** [comment]
IMO event-schema just should be an unconditionally static library (along with all the tiny libraries I created while refactoring) and simply link into libscap.so (there's zero value in having scap_error or scap_platform_util etc. as separate `.so`s IMO)
