### ISSUE TITLE
When docker_connection::get_docker gets container information, the function is stuck in an infinite loop

### ISSUE THREAD

**Issue by zhoujun24** [falcosecurity/libs#1292]
** Describe the bug **
After deploying falco on the machine, it is found that there is no data collection report。
After opening the falco log, the analysis found that every time a container information is pulled, the service will be stuck。
Tracking code, the location is in the docker_connection::get_docker function。
![image](https://github.com/falcosecurity/libs/assets/19777017/bed9cd8b-9caf-47fc-8969-0ee625261ea9)

** How to reproduce it **
I don't know how to reproduce it, I just found this problem, On a machine in my environment, there is a container that cannot pull its information, and no error is reported, and then it will get stuck, and the information of other containers can be pulled normally.
![image](https://github.com/falcosecurity/libs/assets/19777017/4f6be210-e759-4466-bdf5-33c7ea03f074)

** How to solve it **
By setting the timeout period for pulling container information, or the maximum number of retries，such as：
curl_easy_setopt(curl, CURLOPT_TIMEOUT, 3);

**Environment**
Falco version: 0.34.1 (x86_64)
- OS:
CentOS Linux release 7.2 (Final)
- Kernel:
4.14.105
- Installation method:
from source

**Comment by Andreagit97** [comment]
Thank you for reporting this!
> I don't know how to reproduce it, I just found this problem, On a machine in my environment, there is a container that cannot pull its information, and no error is reported, and then it will get stuck, and the information of other containers can be pulled normally.

So if I understood correctly Falco tries to extract info from this particular container and it gets stuck in an infinite loop... 
* do you know by chance if this container has something different from the others?
* does it always happen with this particular container? or for example if you restart falco you won't see it again?

**Comment by zhoujun24** [comment]
> do you know by chance if this container has something different from the others?
Yes, on more than 1,000 machines where falco is deployed, at present, only 1 machines have been found to have this problem

> does it always happen with this particular container? or for example if you restart falco you won't see it again?
Yes, restarted falco many times, every time the service gets this specific container information, it gets stuck

**Comment by Andreagit97** [comment]
thanks! 
Did you solve the issue applying this `curl_easy_setopt(curl, CURLOPT_TIMEOUT, 3);`?
It would be interesting to understand if this container has something different from all the others :thinking:

**Comment by zhoujun24** [comment]
> Did you solve the issue applying this curl_easy_setopt(curl, CURLOPT_TIMEOUT, 3);?

Yes, falco can run normally to collect data
Currently, this specific container is running in the production environment, and I can talk to the business team about its situation

**Comment by Andreagit97** [comment]
Ok, thank you! keep us updated, in the meanwhile, we will try to understand the right way to fix it, if `curl_easy_setopt(curl, CURLOPT_TIMEOUT, 3)` is enough, or maybe we want something else :)

**Comment by FedeDP** [comment]
Hi! Great catch! @zhoujun24 would you mind opening a PR to add your fix? It seems really valuable to me.
/cc @gnosek @deepskyblue86

**Comment by zhoujun24** [comment]
> I opened the PR: #1308 @zhoujun24 I couldn't give the coauthored by since we don't know your name. If you want it, please contact me :)

 @FedeDP Thanks, I want it!

**Comment by FedeDP** [comment]
Oh unfortunately the PR has already been merged, sorry! 
I will make sure to add your name (or github handle if you prefer) to the list of contributors on the release page.
Again, really sorry, we are quickly approaching a release and the PR got merged in a really short period of time!
