### ISSUE TITLE
Update args in `socket` exit event

### ISSUE THREAD

**Issue by Biagio-Dipalma** [falcosecurity/libs#1326]
**Motivation**

In some cases we need to detect network sockets with weird options: for example, an attacker can craft a network socket to steal informations. At the moment we can detect those suspicious options for the socket, but we can't provide details about the network socket (i.e. source IP / dest IP), hence some alerts are not actionable from an investigation point of view. 
Furthermore, we can't filter out events not related to network activity.

**Feature**

A possible solution is to add `domain`, `type` and `proto` args to the exit event of the `socket` syscall. With this change will be possible to detect network sockets with bad arguments in a precise way and provide details about the connection (using the field `fd`)

**Alternatives**

**Additional context**

**Comment by Andreagit97** [comment]
ei @Biagio-Dipalma! The request makes sense! We will try to schedule some time for this in the next release. For the moment I will put the milestone

/milestone TBD

**Comment by Biagio-Dipalma** [comment]
Hey @loresuso , thank you for explaining this, makes sense to me. Closing the issue.
