### ISSUE TITLE
Update args in `prlimit` exit event

### ISSUE THREAD

**Issue by Biagio-Dipalma** [falcosecurity/libs#1327]
**Motivation**

we might need to detect changes to system limits: for example in some cases miners update those limits to optimise their activity. At the moment we can detect this type of changes along with the updated values in the exit event but we can't say which is the resource affected.

**Feature**

I think that the solution here is to add the resource argument to the exit event, in order to define a precise detection and provide useful alerts.

**Alternatives**

**Additional context**

**Comment by Andreagit97** [comment]
ei @Biagio-Dipalma! The request makes sense! We will try to schedule some time for this in the next release. For the moment I will put the milestone

/milestone TBD

**Comment by Andreagit97** [comment]
Probably we need to do the same for `setrlimit` syscall

**Comment by Rohith-Raju** [comment]
I'm working on this 😄
