### ISSUE TITLE
Remove or replace `driver/ppm_syscall.h`

### ISSUE THREAD

**Issue by leogr** [falcosecurity/libs#1346]
**Motivation**

As part of our continuous effort to align with CNCF IP Policy, we requested a license scan. This scan revealed no outstanding issues, but there were a couple of recommended action items.

One reported action item is:

> Action Item 3:  Remove or replace one file that has the GPL-2.0 license.
> -- https://github.com/falcosecurity/libs/blob/master/driver/ppm_syscall.h
> -- NOTE: this file does not have the Linux-syscall-note exception, but appears to be a system header file, however it has a Red Hat copyright.  This file should be removed or replaced to avoid a license conflict.

**Feature**

TBD

**Alternatives**

:thinking: 

**Additional context**

It looks like `ppm_syscall.h` is only require to support kernels `<=2.6.20` cc @Andreagit97

**Comment by Andreagit97** [comment]
yes it is required only to support  kernels `<=2.6.20`
