### ISSUE TITLE
[PROPOSAL] Remove udig engine support

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#1368]
**Motivation**

In the last maintainer call, we discussed whether it is the case to remove the `udig` engine from libscap. The main reason behind this proposal is that today the udig engine is not maintained and broken and unfortunately we have no manpower to maintain it...Removing it will clean and reduce the size of our codebase so I'm in favor of this change.

**Feature**

Remove the `udig` engine from libscap

WDYT? @falcosecurity/libs-maintainers 

You can vote as always with a +1 or -1

This issue is not just for maintainers but also for all adopters to jump in with concerns or blockers, even if as I said `udig` is broken so I don't think we have adopters for it

**Comment by FedeDP** [comment]
+1 from me! Removing dead code is always good to lower maintenance cost.

**Comment by gnosek** [comment]
+1. We can always bring it back (as a first class citizen, unlike now) if there's community interest

**Comment by incertum** [comment]
+1 and thanks for driving this!

**Comment by leogr** [comment]
+1

**Comment by hbrueckner** [comment]
+1 reducing technical debt is always great! Thanks for driving this!

**Comment by incertum** [comment]
@Andreagit97 keep for 0.14.0? Don't see a PR up yet or push to 0.15.0?

**Comment by Andreagit97** [comment]
it's better to have it to avoid conflicts with the release branch in the future :/ this is the PR https://github.com/falcosecurity/libs/pull/1485 a big no-op
