### ISSUE TITLE
[TRACKING] Technical debt cleanup wrt edge case segfaults or memleaks 🧹

### ISSUE THREAD

**Issue by incertum** [falcosecurity/libs#1468]
We can use this ticket to collectively discuss steps we can take to more programmatically attempt to reduce issues related to more corner case segfaults or memory leaks. It's a challenging task for everyone reading this, and we are not planning to rewrite the libraries in Rust at this time.

@falcosecurity/libs-maintainers 
```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/libs/issues/1470
```

**Comment by incertum** [comment]
Raw notes from the 2023-11-02 core maintainers meeting:

- Reject raw pointers? We should still replace them with smart pointers whenever possible. This will make ownership more clear and transparent in libsinsp.
- Pass by parameter or by reference when possible.
- Remove things that are not needed from the core code base first. Removing udig and mesos is more difficult because they are more tangled than removing the old k8s client code base. @jasondellaluce volunteered to tackle this (mesos + k8s client removal after we have the new k8s client implementation -> coordinate with @Andreagit97).
- Consider prioritizing removing the respective code lines in `sinsp next` first. (@gnosek comment)

**Comment by LucaGuerra** [comment]
From the meeting, as a practical item we mentioned the work we started to support UndefinedBehaviorSanitizer (and we can continue with more sanitizer/safeguards), I have created an issue for it: https://github.com/falcosecurity/libs/issues/1470

**Comment by leogr** [comment]
What are the next steps here?

**Comment by incertum** [comment]
I think we have 5+ folks currently cleaning the code base like crazy in many corners, which is amazing :rocket:

**Comment by FedeDP** [comment]
remove-lifecycle rotten
