### ISSUE TITLE
Running sinsp may fail to evaluate user name base on user id

### ISSUE THREAD

**Issue by tzachiabo** [falcosecurity/libs#149]
**Describe the bug**

Running sinsp may fail to evaluate user name 
This cause due to two main issues:
1) sinsp evaluating the user list just once on init phase, creating a user after the init phase will cause sinsp to fail evaluating the user name

2) sinsp user list is not working with container context, the user list is being evaluated by reading /etc/passwd file, using  getpwent/setpwent, however this file may be unique per container. ie reading this file in the context of the Sysdig container is not enough for build the user list, A possible solution may be having user list per container instead of per the whole system.

**How to reproduce it**

Running Sysdig cli from one container, and from a different container run "useradd newuser; su newuser -c "ls -l"

**Expected behaviour**

The user that run "ls -l" should be newuser and not "<NA>"

**Screenshots**
From 1 container
![image](https://user-images.githubusercontent.com/17710486/144597715-57e56f27-2c66-462a-a722-3d62d9313f61.png)

From sysdig
![image](https://user-images.githubusercontent.com/17710486/144597658-7c6480f4-903d-4099-ab00-d40874e68c79.png)

**Comment by tzachiabo** [comment]
Hi @FedeDP,

Thanks for the response
When the Falco 0.32 is expected to be released?

You have mentioned a mechanism for internal events and gave example for "PPME_USER_ADDED"
I did not find the word PPME_USER_ADDED in this repo
could you explain to me how the internal events are working?

**Comment by FedeDP** [comment]
Hi @tzachiabo !
Falco 0.32 is the release after the next one; 0.31 will be released before around the end of january; then we can start working on new "big things", like this one (that while it does not seem that big, it indeed is, as it touches multiple areas) for the 0.32 release that it is expected for the end of May.

PPME_USER_ADDED is still not present, it is just an implementation idea! If you wish to see a similar mechanism, you should look for `PPME_CONTAINER_JSON_2_E` event: it is the internal event that is emitted when a new container is detected. 
As you can imagine, this is essentially needed because all the dynamic state (ie: not the booting environment) must be propagated through events to allow dumped scap files to be able to rebuild the dynamic environment without worries.
Thus, events like "new user added" should be encapsulated in an event, emitted, and then managed internally updating the internal system view.

I hope I was able to explain myself :)

**Comment by FedeDP** [comment]
@tzachiabo i am writing just to let you know that this issue is currently in progress; i am quite ready to open the PR indeed! 
We should still be on target for the 0.32.0 release :muscle:

**Comment by FedeDP** [comment]
Opened the PR ;) 
https://github.com/falcosecurity/libs/pull/220

There is a limitation though: we are not able to fetch user/group information from containers; this means that for containers users/groups we will only be able to fetch uid/gid, but not user name, user home etc etc.  
There is nothing we can do for that unfortunately.  
All in all, at least we fix 2 issues:
* dynamic users/groups support
* we won't mix up users/groups between host and containers

**Comment by tzachiabo** [comment]
@FedeDP Could you share with me why we can't user/group information?
As far as I understand. The data exists under /etc/passwd file under the scope of the container

**Comment by loresuso** [comment]
Hi @FedeDP, I have seen your PR on this and it is amazing!
However, I think @tzachiabo is right, maybe there is a way to get the usernames from the `/etc/passwd` file inside the container. One way to do so is by inspecting the overlay filesystem to access that file: to try it, just add a user inside a container, then do `cat /etc/mtab`. Look for the overlay entry and in particular the `upperdir`. You will find something like `/var/lib/docker/overlay2/544fc9eb63f4531c74e364f469795b6b4538e5ebaea32bf558f839997935c599/diff/`. Then, you can navigate there from the host and you will find the file `/etc/passwd` that was modified inside the container.

This is just a random idea, I may be completely wrong, feel free to tell me what do you think! 🙂

**Comment by FedeDP** [comment]
Hi @loresuso ! Thanks for the tip!
Unfortunately, it seems i am not able to make it work using docker as normal user; perhaps you've got some more knowledge on this? 
Moreover, each container runtime would possibly behave differently. The PR is already quite huge; i think that we can give this a shoot in a following PR.
WDYT?

**Comment by loresuso** [comment]
Yeah, I agree with you. This is not an easy task, and different container runtimes can make it harder, even if I think that most runtimes use overlayfs under the hood. Let's give it a try once your PR got merged!
