### ISSUE TITLE
Under the arm architecture，function perf_event_mmap error happened

### ISSUE THREAD

**Issue by zhenpeng2018** [falcosecurity/libs#1507]
The following error occurred during startup
Error:unable to mmap the perf-buffer for cpu '0','65536','22':Invalid 
After investigation, it was found that the mapping error occurred in the function perf_event_mmap（userspace/libscap/engine/bpf/scap_bpf.c）.
Why does a file descriptor map two segments of memory?
Hope to hear from you soon

- Falco version:
0.36

- Kernel:
-4.19 rhel

```[tasklist]
### Tasks
```

**Comment by Andreagit97** [comment]
ei @zhenpeng2018 thank you for reporting! You are probably using a buffer too big and you cannot allocate this memory.  You can find more info about the buffer dimension to choose from here: https://github.com/falcosecurity/falco/blob/0.36.2/falco.yaml#L807

How much RAM do you have on your node/local machine?

> Why does a file descriptor map two segments of memory?

The buffer memory is mapped twice to handle events that wrap around the ring buffer easily. With just one mapping it would be difficult to handle events that have one part at the end of the buffer and the remaining part at the beginning (we are talking about circular buffers)
