### ISSUE TITLE
`k8s.*` fields must be populated only if event originate from within a Kubernetes environment

### ISSUE THREAD

**Issue by leogr** [falcosecurity/libs#1532]
**Motivation**

See https://github.com/falcosecurity/libs/pull/1489#pullrequestreview-1755900817

> ... `container.ip` and `k8s.pod.ip` yielding the same value is justified as they represent the same concept in their respective contexts (a container's IP in a pod matches the pod's IP). However, this should be true only when the event happens in a Kubernetes environment. **It does not make sense to get a value from `k8s.pod.ip` when the event comes from a container that is not running in Kubernetes.**

**Feature**

All `k8s.*` fields should return NA if the event does not originate from a Kubernetes environment. 
(currently, some fields may return some non-null values since the data is collected from the container runtime).

**Alternatives**

An alternative could be to avoid field aliasing. However, having fields that return the same value (under some circumstance) seem semantically legit.

**Additional context**

See https://github.com/falcosecurity/libs/pull/1489#pullrequestreview-1755900817

**Comment by incertum** [comment]
/milestone 0.14.0

Done. We addressed this in a new PR alongside some other improvements.
