### ISSUE TITLE
Unexpected setuid call by non-sudo events contain no details

### ISSUE THREAD

**Issue by manojdeshmukh45** [falcosecurity/libs#1630]
In the falco alerts "Unexpected setuid call by non-sudo events contain no details" is comming all <NA>

00:40:51.862247143: Notice Unexpected setuid call by non-sudo, non-root program (container_name=host user= user_loginuid=-1 cur_uid=4294967295 parent=<NA> command=<NA> pid=1224253 uid=<NA> container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host

![image](https://github.com/falcosecurity/falco/assets/35873736/259134e2-5a86-454f-baa4-334b39c0629f)

**Environment**

- Falco version:
{"default_driver_version":"4.0.0+driver","driver_api_version":"3.0.0","driver_schema_version":"2.0.0","engine_version":"16","falco_version":"0.34.1","libs_version":"0.10.4","plugin_api_version":"2.0.0"}
- System info: 
Falco version: 0.34.1 (x86_64)
- Cloud provider or hardware configuration: GCP
- OS: NAME="Debian GNU/Linux"
- Kernel:
Linux <podname> 5.10.176+
- Installation method:

**Comment by Andreagit97** [comment]
How to reproduce it with `sinsp-example`

1. Build sinsp-example in full mode, not minimal! Minimal build doesn't know about containers so it tries to fallback on the host and by luck it resolves it correctly!
2. Type the following command
```bash
sudo ./libsinsp/examples/sinsp-example \
    -o "user_id=%evt.rawarg.uid user_name=%evt.arg.uid" \
    -f "evt.type in (setuid) and evt.dir=> and container.id!=host" --modern_bpf
```

**Comment by FedeDP** [comment]
Yep, IMHO this is not a bug: if user 1000 is not existing in the container, it is fine to return NA username, right? 
At the same time, if you enforce an existing (in the container) user, everything works fine.

**Comment by Andreagit97** [comment]
> Yep, IMHO this is not a bug: if user 1000 is not existing in the container, it is fine to return NA username, right?

Uhm IMO Falco should try to give the right user since it runs on the host and has the possibility to see all the users...

> Edit: we might add a fallback lookup for the uid/gid on the host when the container has no such uid/gid perhaps.

This could be an idea, I am not sure if there are other cases when the user is not defined inside the container but it doesn't correspond to any user on the host, I don't think so :thinking: So the fallback might be ok! @deepskyblue86 WDYT?

**Comment by FedeDP** [comment]
But please note:
```
docker run --rm --user 1000 busybox whoami
whoami: unknown uid 1000
```

I still think `NA` is the proper answer here.

**Comment by Andreagit97** [comment]
yeah, docker knows nothing about user 1000 because is a user outside the container, but Falco as an external tool has the knowledge to understand who is the real user...the downside of leaving all as it is is that all the processes inside the containers will have `user.name` = `<NA>` :/

**Comment by FedeDP** [comment]
Is anybody still experiencing issues on Falco 0.37?
Moving to milestone 0.18.0, but ready to close this one if the issue is gone.
/milestone 0.18.0

**Comment by Andreagit97** [comment]
The decision of closing or not this is on us... we identified the issue, if we decide that we are fine with the `<NA>` since the container cannot see the external user, i think we can close it

**Comment by FedeDP** [comment]
I think so, as i explained earlier it would be wrong to state the opposite since if the user is not existent in the container, it is to all effects `NA` to it.
/milestone 0.17.0
/close
