### ISSUE TITLE
[TRACKING] End-to-End Test Contribution Proposal

### ISSUE THREAD

**Issue by therealbobo** [falcosecurity/libs#1650]
**Motivation**

As consumers of `libs`, we have developed a comprehensive set of end-to-end tests that have proven valuable in ensuring the reliability and functionality of `falcosecurity/libs`, particularly in conjunction with various drivers. Recognizing the benefits of community collaboration, we aim to upstream these tests to the `falcosecurity/libs` repository.

**Feature**

We propose the contribution of a set of private end-to-end tests specifically designed to validate the behaviour of `libsinsp` together with the associated drivers. These tests aim to cover critical scenarios, ensuring that the library performs optimally in various environments.

**Additional Context**

The proposed end-to-end tests cover a spectrum of scenarios, including but not limited to:

- Interaction of `libsinsp` with various drivers.
- Comprehensive coverage of edge cases and error scenarios.

These tests cover various areas of `libsinsp` interest, like:
- [x] processes
- [x] syscalls
- [x] cgroups
- [x] container runtimes
- [x] networking

To facilitate this process, we are creating this tracking issue to serve as a central point for discussion and coordination with the maintainers of `falcosecurity/libs`.

**Comment by incertum** [comment]
Amazing @therealbobo, thanks for taking the lead on tracking this!

Re container runtimes cross-linking to https://github.com/falcosecurity/libs/issues/1298. Looking forward to seeing e2e tests expansions!

**Comment by FedeDP** [comment]
@therealbobo what's the status of this one? Can you update the body?

Anyway, moving to 0.17.0 because the effort is not over yet!
/milestone 0.17.0

**Comment by Andreagit97** [comment]
what is missing here @therealbobo ?

**Comment by therealbobo** [comment]
There's only a PR left (which is already open) but I was asked to fix the flaky tests first. I looked into them but didn't find a solution yet.

**Comment by FedeDP** [comment]
I don't think we will make it for 0.18, let's move this to 0.19!
/milestone 0.19.0

**Comment by therealbobo** [comment]
This last PR https://github.com/falcosecurity/libs/pull/1958 ends this contribution. :)
