### ISSUE TITLE
 [Proposal] Chisels removal from libs

### ISSUE THREAD

**Issue by leogr** [falcosecurity/libs#1743]
**Motivation**

Since its introduction in 2021 as part of [the drivers and libs contribution to Falco](https://falco.org/blog/contribution-drivers-kmod-ebpf-libraries/), the chisels feature has seen no adoption and no plans for future use by Falco. Its maintenance now outweighs its benefits, making it an unnecessary burden.

**Proposal**

Thus, I suggest removing the [chisel implementation](https://github.com/falcosecurity/libs/tree/master/userspace/chisel) from libs. 

This proposal is based on its limited use (we are only aware of  [sysdig cli](https://github.com/draios/sysdig), from which the implementation initially came). Eventually, consumers still utilizing chisels may incorporate this feature into their own repositories if they want.

Since we are pretty confident this is not going to create any user disruption, I would like to take this tentatively for:
/milestone 0.16.0

**Alternatives**
  
Doing nothing is always an option. However, this wouldn't offer any advantage and would continue to divert resources from more impactful areas of the project.

**Comment by leogr** [comment]
cc @falcosecurity/libs-maintainers Let me know if you disagree :pray:

**Comment by incertum** [comment]
Agreed -> remove chisels from libs.

**Comment by FedeDP** [comment]
Agree! :+1: from my side.

**Comment by Andreagit97** [comment]
+1!
