### ISSUE TITLE
BPF probe compile once run everywhere with BTF

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/libs#186]
This will likely become a proposal if it receives a good feedback here (like doing a :+1: counts as feedback ) 

**What would you like to be added**:

Adapt and compile our eBPF probe loader code to the BPF type format (BTF) - links below.

**Why is this needed**:

*Some considerations first*
One of the main barriers that new and old users encounter when trying to adopt falco is building either the kernel module or the BPF probe. To mitigate this we’ve been working on two main efforts over time:
- doing containerized builds to minimize the host dependencies
- having pre built kernel modules for a wide variety of kernels 

Despite this, many users still struggle and in my opinion the experience in that area has a lot of room of improvement. 

Moreover, in new-ish environments (recent kernel 4 and 5) using eBPF is becoming more and more common and honestly I expect that to become the default for Falco at some point. This also makes sense from a privileges point of view where we will only need capabilities for the `bpf` syscall .

*Summary of Problems with our current approach*

- difficult to just run falco because the compilation or the download might not go right 
- kernel headers need to be installed on every host along with the clang tool chain that processes them
- sometimes having kernel headers and tool chain is just very hard or impossible (immutable environments)
- compiling is complicated, a single mistake and the user can’t load the loader and falco becomes useless
- wider attack surface because having to compile stuff for the kernel requires a tool chain in a container that can read kernel folders (e.g `/lib/modules`)
- difficult to distribute the “kernel side” of falco 

*The actual idea*
After all these considerations I think that we need to adapt our current programs to take advantage of BTF (links below) in order to be able to compile once and run everywhere. 

Read more about BTF here: https://www.kernel.org/doc/html/latest/bpf/btf.html and here https://facebookmicrosites.github.io/bpf/blog/2018/11/14/btf-enhancement.html

*Next steps* 
After gathering some initial feedback here with this message I’ll open a formal proposal with an action plan

**Comment by jnach** [comment]
The business need is and I think always will be a moving target here, libs or not. You can:
A: Solve for unknown kernel with (likely) BTF, libs or not, it's still compiled for a specific kernel version. Maybe there is some kind of hook possible to hang with updates? It's hard to say. 
B: Have kernel solve for you by supporting specific versions, which is also difficult from an update/security perspective as an offering.

**Comment by Andreagit97** [comment]
Hi all 🖖 I wrote down some ideas about a new BPF probe [here](https://github.com/falcosecurity/libs/pull/268). If you are interested, you can take a look here :eyes:

**Comment by jundizhou** [comment]
We are using the software in depth. Do you have any plans to replace libbpf.

**Comment by leogr** [comment]
@FedeDP @Andreagit97 do we have another issue for tracking this?

**Comment by Andreagit97** [comment]
We had this one https://github.com/falcosecurity/libs/issues/513 to track the syscall support of the modern BPF probe, and now we have this PR  https://github.com/falcosecurity/falco/pull/2282 in Falco, that I will enrich with some info when we will be ready to release modern bpf packages

**Comment by leogr** [comment]
Closing in favor of #513 

/close
