### ISSUE TITLE
[BUG] Broken plugins metrics support

### ISSUE THREAD

**Issue by mrgian** [falcosecurity/libs#1888]
`libs 0.17.0` introduced the support for plugin-provided metrics in the plugin API.
However, **this new feature is currently broken and should not be used**.

Even if present in the plugin API (https://github.com/falcosecurity/libs/blob/master/userspace/plugin/plugin_api.h), the symbol `get_metrics` should not be implemented by plugins.

The issue lies in the symbol `get_metrics` (https://github.com/falcosecurity/libs/blob/master/userspace/plugin/plugin_api.h#L979) not being registered when the plugin is loaded.
For this reason `sinsp` will ignore any metric provided by plugins using this feature.

**Comment by incertum** [comment]
This has already been fixed in 0.17.x
