### ISSUE TITLE
Building on musl fails to link against libanl when not using static linking (aka MUSL_OPTIMIZED_BUILD)

### ISSUE THREAD

**Issue by hhoffstaette** [falcosecurity/libs#1948]
**Describe the bug**

sysdig can be built with `MUSL_OPTIMIZED_BUILD` - unfortunately this is misleading as it implies static linking and statically built dependencies, which is not necessary on musl.
I found that using a regular build against unbundled dependencies on musl fails, as falcosecurity-libs tries to unconditionally link against `libanl`, which does not exist on musl.

**How to reproduce it**

Build sysdig on musl with `MUSL_OPTIMIZED_BUILD` **disabled** and unbundled dependencies built as shared libs. It should error out with a failure to link `-lanl`.

**Expected behaviour**

sysdig should build successfully on musl against shared unbundled dependencies.

**Environment**

- musl 1.2.5 in a Gentoo chroot (with musl as system C library)

- Installation method: from source - I am the package maintainer :)

**Additional information**

We had to fix this in Gentoo for an older version in this commit:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=844fbd1e96beda0fb94ea06aba8f2618bfdad1f7

**Comment by hhoffstaette** [comment]
For libs-0.17.2 I had to rebase the patch (while finally updating our sysdig package to 0.38.0) and it looks like this:

```
--- libs-0.17.2/userspace/libsinsp/CMakeLists.txt~	2024-06-14 11:38:50.000000000 +0200
+++ libs-0.17.2/userspace/libsinsp/CMakeLists.txt	2024-07-05 00:18:03.326406540 +0200
@@ -258,8 +258,8 @@ if(NOT WIN32)
 			)
 
 			if(NOT MUSL_OPTIMIZED_BUILD)
-				target_link_libraries(sinsp INTERFACE rt anl)
-				list(APPEND SINSP_PKGCONFIG_LIBRARIES rt anl)
+				target_link_libraries(sinsp INTERFACE rt)
+				list(APPEND SINSP_PKGCONFIG_LIBRARIES rt)
 			endif()
 
 		else()
```

Obviously this is not correct on glibc systems, so the patch is only applied conditionally when building on musl. Can we somehow sanitize this without breaking things?

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue :) 
Mmh perhaps we could only link `anl` if we can find it in the system? Likely using `find_library` ?

**Comment by FedeDP** [comment]
Opened https://github.com/falcosecurity/libs/pull/2036 to fix this ;)
