### ISSUE TITLE
Fix fd filtercheck fallback in case of  `openat*` events involving `dirfd` parsing

### ISSUE THREAD

**Issue by incertum** [falcosecurity/libs#2039]
Follow up to https://github.com/falcosecurity/libs/pull/1993#discussion_r1738462593

I believe we need another small fix in another PR for the fd filtercheck fallback in case of  `openat*` events involving `dirfd` parsing ...

https://github.com/falcosecurity/libs/blob/5ed00b2a9a627d9a6263369edfdcbaf5cc6b1485/userspace/libsinsp/sinsp_filtercheck_fd.cpp#L242

aka since we do change the state (as @LucaGuerra helped pointing out) it seems to me that we also need to rewrite the fd info with all concatenated paths etc to the cache, similar to the parsers logic here: https://github.com/falcosecurity/libs/blob/5ed00b2a9a627d9a6263369edfdcbaf5cc6b1485/userspace/libsinsp/parsers.cpp#L2784

---

Plus there are not many `fd.name` unit tests. In this PR https://github.com/falcosecurity/libs/pull/1993 we introduce a wider test scope for `fs.path.*` fields and also compare them to the `fd.name` field if applicable.

CC @LucaGuerra thanks a bunch in advance!

**Comment by FedeDP** [comment]
Oh i saw this one while working on #1993; IMHO it is correct as-is because we reach that point only when `evt->fdinfo` is null; in that case it is ok to manually get `dirfd` argument from the event itself, and use it to fetch the parsed dirfd path; note also that my last commit in #1993 made `sinsp_parser::parse_dirfd` stateless, ie: event is not changed anymore.
I think we can consider this fixed as part of #1993 .

**Comment by FedeDP** [comment]
> Plus there are not many fd.name unit tests. In this PR https://github.com/falcosecurity/libs/pull/1993 we introduce a wider test scope for fs.path.* fields and also compare them to the fd.name field if applicable.

Of course, agree about the tests, we should add them!

**Comment by incertum** [comment]
> Oh i saw this one while working on #1993; IMHO it is correct as-is because we reach that point only when `evt->fdinfo` is null; in that case it is ok to manually get `dirfd` argument from the event itself, and use it to fetch the parsed dirfd path; note also that my last commit in #1993 made `sinsp_parser::parse_dirfd` stateless, ie: event is not changed anymore. I think we can consider this fixed as part of #1993 .

I do agree that this change is a better behavior than what was done before and "no bugs" like before. Thank you!

**Comment by LucaGuerra** [comment]
Added an extra test, if all passes we should be good to go 🚀
