### ISSUE TITLE
Tons of build issues with missing field initializers

### ISSUE THREAD

**Issue by gnosek** [falcosecurity/libs#2052]
**Describe the bug**

When building with -Werror, I'm getting literally hundreds of errors related to missing designated field initializers:

```
.../test/drivers/test_suites/syscall_exit_suite/sendto_x.cpp:18:81: error: missing initializer for member ‘send_data::greater_snaplen’ [-Werror=missing-field-initializers]
   18 |         evt_test->client_to_server_ipv4_tcp(send_data{.syscall_num = __NR_sendto});
```

AFAIK partial initialization with designated initializers isn't valid C++ (which doesn't make any sense but here we are).

**How to reproduce it**

Hmm, just build with -DCMAKE_BUILD_WARNINGS_AS_ERRORS=On, I suppose.

**Expected behaviour**

I expected a successful build.

**Screenshots**

I'm not pasting all the errors here, it's literally hundreds and hundreds.

**Environment**

```
$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Additional context**

I'm hoping we can find some compiler-flag based solution (a gcc extension maybe), because otherwise we're looking at an insane number of patches like this one:

```
 	/*=============================== TRIGGER SYSCALL  ===========================*/
 
-	evt_test->client_to_server_ipv4_tcp(send_data{.syscall_num = __NR_sendto, .greater_snaplen = true},
-					    recv_data{.syscall_num = __NR_read});
+	evt_test->client_to_server_ipv4_tcp(
+	        send_data{.syscall_num = __NR_sendto, .greater_snaplen = true, .null_sockaddr = false},
+	        recv_data{.syscall_num = __NR_read,
+	                  .null_sockaddr = false,
+	                  .null_receiver_buffer = false,
+	                  .skip_recv_phase = false});

```

Switching to C++20 just causes *more* errors. Don't ask me why or how (this file is C, not C++) but then it also complains about https://github.com/falcosecurity/libs/blob/master/userspace/libscap/linux/scap_cgroup.c#L796 mixing designated and non-designated initializers (that one could just be `{}` I guess).

Also, am I the only one in the world building with -Werror or is my compiler sufficiently different from whatever is used in CI?

cc @Andreagit97 @federico-sysdig

**Comment by Andreagit97** [comment]
Ei great catch! thank you! Reading the doc this is not super clear https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers

> For a non-union aggregate, elements for which a designated initializer is not provided are initialized the same as described above for when the number of initializer clauses is less than the number of members (default member initializers where provided, empty list-initialization otherwise)

I agree to enable` -DCMAKE_BUILD_WARNINGS_AS_ERRORS=On` by default in CI!
