### ISSUE TITLE
Fedora 40 - libscap: bpf_load_program() event=raw_tracepoint/filler/sys_poll_x: Operation not permitted

### ISSUE THREAD

**Issue by albe19029** [falcosecurity/libs#2094]
When I build bpf driver on fedora:40 image and then try to run it it get next error:

libscap: bpf_load_program() event=raw_tracepoint/filler/sys_poll_x: Operation not permitted

On fedora:39 and older everything is working OK.

I have checked the code, and this patch resolved issue:
[fedora40.patch](https://github.com/user-attachments/files/17289169/fedora40.patch)

Probably it is because of update of clang, as in version fedora:39 we have clang-17.0.1, and in fedora:40 we have clang-18.1.8.

Is it possible to add this path to master, to be able to build correct bpf driver for fedora:40 and higher, as in fedora 41 it is not working now also.

**Comment by albe19029** [comment]
Here is my  PROG LOAD LOG:

[prog_load_log.txt](https://github.com/user-attachments/files/17289231/prog_load_log.txt)

**Comment by Andreagit97** [comment]
ei @albe19029 thank you for this! Usually we suggest to use the modern-ebpf with recent distros like fedora 40/41 but since the patch you are proposing seems really simple we could apply it, WDYT @FedeDP ?

**Comment by FedeDP** [comment]
Oh wow, yep the patch is really small! @albe19029 care to open a PR?

**Comment by albe19029** [comment]
Created pull request https://github.com/falcosecurity/libs/pull/2095
