### ISSUE TITLE
Allow the userspace libs to specify a driver at runtime

### ISSUE THREAD

**Issue by dwindsor** [falcosecurity/libs#245]
It would be useful to be able to load custom named drivers (e.g. `falco-acme`) alongside the stock driver (`falco`).

Currently, this isn't possible because stock libscap is unable to connect to custom-named Falco drivers. This happens because libscap sets the name of the driver at compile time via the environment variable `DRIVER_DEVICE_NAME`.

From [`scap_open_live_int()`](https://github.com/falcosecurity/libs/blob/84470f1621d143c8cdc24fdf9bb4c5b87180ea6c/userspace/libscap/scap.c#L161):

```c
//
// Open the device
//
snprintf(filename, sizeof(filename), "%s/dev/" DRIVER_DEVICE_NAME "%d", scap_get_host_root(), all_scanned_devs);
```

**Feature**

We need to add support for runtime selection of a driver by name.

This can be accomplished by adding a parameter to e.g. `scap_open_int_live()` and `sinsp_open()` containing the driver name:

```c++
sinsp s;

try
{
    // First, try connecting to a custom-named driver.
    s.open("acme-falco");
 }
 catch (sinsp_exception &ex)
 {
    driverLoaded = false;
 }
 
 if (!driverLoaded)
 {
    try
    {
        // If unable to connect to a custom-named driver, try the stock driver.
        s.open("falco")
    }
    catch (sinsp_exception)
    {
    }
}

**Alternatives**

**Additional context**

**Comment by FedeDP** [comment]
I think it makes sense!
We might add an optional param to `sinsp::open()` to retain backward compatibility; then add a new field to `scap_open_args`.

Would you be open to contribute? ;) 
Thanks!
