### ISSUE TITLE
Supporting Syscalls introduced in VFS: file system context

### ISSUE THREAD

**Issue by Osherz5** [falcosecurity/libs#269]
**Motivation**

Containerization is growing among the Linux developers, and new Syscalls were introduced in order to handle virtual filesystem using context.

**Feature**

Add support for the following new Syscalls that were introduced in Linux kernel 5.2 
- fsconfig
- fsmount
- fsopen
- fspick

**Alternatives**
There are no current alternatives, since these Syscalls are not supported and show up as "unknown".

**Additional context**
fsconfig patch:
https://patchwork.kernel.org/project/linux-fsdevel/patch/153313723557.13253.9055982745313603422.stgit@warthog.procyon.org.uk/

https://lwn.net/Articles/780267/

https://patchwork.kernel.org/project/linux-fsdevel/list/?series=4245&state=%2A&archive=both

**Comment by FedeDP** [comment]
Thanks @Osherz5!
I am tagging a couple of guys who can help with this! 
/cc @andreabonanno @loresuso @Andreagit97 

Thanks for the heads up!

**Comment by jasondellaluce** [comment]
Closing this as this is tracked by the umbrella issue in Falco!
