### ISSUE TITLE
Build fail when using external, non-bundled Curl library

### ISSUE THREAD

**Issue by federico-sysdig** [falcosecurity/libs#310]
When building the Falco libs using externally provided libraries (e.g. from the Linux distro or a package manager) there is a problem related to the name of the _CMake_ variable `CURL_INCLUDE_DIR` that should be `CURL_INCLUDE_DIRS` as defined internally in the library `libcurl`. The problem starts at this _CMake_ script line.

https://github.com/draios/agent-libs/blob/3969c0f5c948d145c6493148a9271eb33d3879be/cmake/modules/curl.cmake#L15

**How to reproduce it**

Make sure you have a distribution of `libcurl` that can be reached within _CMake_ using `find_package(CURL REQUIRED)`, set the _CMake_ variable `USE_BUNDLED_CURL` to off and start the build, which will break during _CMake_ configure/generate steps.

**Expected behaviour**

The build should succeed. The variable `CURL_INCLUDE_DIR` should be changed everywhere to `CURL_INCLUDE_DIRS` to match the one from Curl.
To be honest, after a second look, I noticed that old versions of `libcurl` have both names, but more recent version of it have removed the one used in Falco libs. This change will increase Falco compatibility with respect to different versions of `libcurl`.

**Environment**

- Falco version: not sure... the commit-id is 3969c0f5c948d145c6493148a9271eb33d3879be

/assign @leogr

**Comment by leogr** [comment]
Nice catch and thank you for having reported this :+1: 

I totally agree that the variable should be renamed according to the latest `libcurl` to achieve greater compatibility. 
Indeed, here is the fix :point_right: https://github.com/falcosecurity/libs/pull/312

:smiley:
