### ISSUE TITLE
Coding style for `libs` repo

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#381]
**Motivation**

Hi folks! I think we have to introduce a definitive coding style for this repository. The number of lines continuously grows and sometimes becomes difficult also to understand the code without a specific standard! 
In this repo, we already have a configuration file for `clang-format` and VScode offers an amazing extension that allows us to format our file in a very simple way. 
The rationale here is to introduce a CI/CD job that checks the coding style of every new Pull request and denies the merge until the code respects the conventions.
The initial discussion is started [here](https://github.com/falcosecurity/libs/pull/373) but I think we need a dedicated thread for it.
It would be great to put together some ideas here!

**Feature**

Introduce a CI/CD job that checks the coding style of every new Pull request and denies the merge until the code respects the conventions.

**Comment by Andreagit97** [comment]
cc @leogr @Molter73

**Comment by Molter73** [comment]
Big +1 from me, having coherent code is always nice. I also have no strong opinions on what the style should be, but I do feel strongly that it must be properly enforced through a CI job as stated, so the existing clang-format file looks good to me.

Further more, in order to not force people to use vscode for formatting, we might want to consider adding some sort of make target or script that runs `clang-format` locally so validation before committing is easily done. As an example, this is how we handle code formatting in stackrox/collector: https://github.com/stackrox/collector/blob/b3ff69b6d5a86eba00c25a8569a79c2f77546612/collector/Makefile#L64-L74. Bonus points if we provide a `pre-commit` hook for checking style so contributors don't have to do the mental exercise of remembering to format the code before committing.

**Comment by Andreagit97** [comment]
> Big +1 from me, having coherent code is always nice. I also have no strong opinions on what the style should be, so the existing clang-format file looks good to me. I do feel strongly that style must be properly enforced through a CI job as stated.
> 
> Further more, in order to not force people to use vscode for formatting, we might want to consider adding some sort of make target or script that runs `clang-format` locally so validation before committing is easily done. As an example, this is how we handle code formatting in stackrox/collector: https://github.com/stackrox/collector/blob/b3ff69b6d5a86eba00c25a8569a79c2f77546612/collector/Makefile#L64-L74. 

We absolutely need a script or a make target!

> Bonus points if we provide a `pre-commit` hook for checking style so contributors don't have to do the mental exercise of remembering to format the code before committing.

This would be amazing in my opinion! :rocket:

**Comment by deepskyblue86** [comment]
This might be useful: https://github.com/muttleyxd/clang-tools-static-binaries

**Comment by incertum** [comment]
Proposing to schedule this and commit to it (also the reviewers) and then agree to a v1 we actually merge. WDYT @Andreagit97 we definitely need this?

**Comment by leogr** [comment]
I suggest scheduling this for immediately after we secure the Falco 0.36 release. Approximately between mid-Sept and early Oct. wdyt?

**Comment by incertum** [comment]
> I suggest scheduling this for immediately after we secure the Falco 0.36 release. Approximately between mid-Sept and early Oct. wdyt?

Sounds perfect to me!

**Comment by incertum** [comment]
@Andreagit97 and @leogr kindly checking in on this as it's Nov 🙃 ty!

**Comment by Andreagit97** [comment]
At the moment I have no time to work on this and moreover, we are near the `0.14.0` release, unfortunately, it is not a great moment to go on with this :(

**Comment by incertum** [comment]
👍 Let's discuss in our next strategy meeting how we can support each other to get this over the finish line.

**Comment by leogr** [comment]
May we revamp this once 0.38 is out? :thinking:

**Comment by Andreagit97** [comment]
/remove-lifecycle stale


@falcosecurity/libs-maintainers  I will try to find some time at the end of August to address at least the formatting using clang-format! The ideal thing would be to have this as one of the latest commits before 0.18.0 to avoid issues with cherry-picks

**Comment by Andreagit97** [comment]
let's wait until we really format all the code

**Comment by leogr** [comment]
:partying_face:
