### ISSUE TITLE
Build failure on riscv64 and patch

### ISSUE THREAD

**Issue by dkogan** [falcosecurity/libs#399]
Hi. I'm maintaining this for Debian. There's a build failure on riscv64, fixed with this patch:

https://salsa.debian.org/debian/falcosecurity-libs/-/blob/master/debian/patches/fix-riscv64-ftbfs.patch

Thanks

**Comment by FedeDP** [comment]
Hi! Thanks for the patch! Are you willing to open PR for it?
Btw note that at the moment only x86_64 is officially supported, and Arm64 support is ok its way.
This means that even if libs actually builds, there is no guarantee that they correctly work.

Thank you very much!

**Comment by dkogan** [comment]
Hi. If you just merge the patch yourself, that'd be awesome. I don't actually use riscv64, and haven't tested this past the build fix. Somebody will hopefully file a Debian bug report if it doesn't work.

**Comment by Andreagit97** [comment]
No problem @dkogan, I will open the pull request putting you as co-author since you provide also the solution to the issue, IMHO this is a reasonable patch that wouldn't cause any issue to our libs
