### ISSUE TITLE
Driver API version and schema version must be bumped before the first tagged release.

### ISSUE THREAD

**Issue by leogr** [falcosecurity/libs#435]
**Motivation**

Falco 0.32.0 uses [39ae7d](https://github.com/falcosecurity/libs/tree/39ae7d40496793cf3d3e7890c9bbdc202263836b/driver) as driver version. The schema version has changed (and maybe the API version too) since then.

**Feature**

Bump API version and schema version according to [our versioning rules](https://github.com/falcosecurity/libs/blob/master/release.md#drivers-versioning).

**Alternatives**

**Additional context**

This means that the first version of the driver can't be 1.0.0

**Comment by FedeDP** [comment]
* Schema: 2.0.0 -> [dup change](https://github.com/falcosecurity/libs/pull/385) is incompatible with previous.
* Api: 1.0.0

This means we will be tagging drivers 2.0.0+driver.
