### ISSUE TITLE
probe init err: bpf_load_program() err=28 event=filler/sys_autofill message=0

### ISSUE THREAD

**Issue by winston-xing** [falcosecurity/libs#462]
I use deepin20.6,run load bpf;  throw a error  init err: bpf_load_program() err=28 event=filler/sys_autofill message=0

**Comment by FedeDP** [comment]
Hi! Can you share some more info, like the kernel version, the libs version and the full output?
Thank you very much!

**Comment by FedeDP** [comment]
I think we fixed a couple of similar issues:
* https://github.com/falcosecurity/libs/pull/316
* https://github.com/falcosecurity/libs/pull/317

And 316 is exactly your error code (28).

**Comment by Andreagit97** [comment]
Hi @winston-xing any news here?
