### ISSUE TITLE
kernel module fails to parse connect events to abstract unix sockets #1758

### ISSUE THREAD

**Issue by HybridReaverHD** [falcosecurity/libs#47]
there can be abstract unix sockets in which the sockaddr_un ->sun_path will start with \x00 (NULL_TERMINATOR)
in those cases the kernel module fails to parse the unix socket name (since it start with a terminator) and the fd.name becomes empty

links:
abstract unix sockets - [Link](https://unix.stackexchange.com/questions/206386/what-does-the-symbol-denote-in-the-beginning-of-a-unix-domain-socket-path-in-l)
how strace handles this - [Link](https://github.com/strace/strace/blob/fcd88d188802a8628b465ebd4d5561564d3552bd/src/sockaddr.c#L57)

from strace:
![image](https://user-images.githubusercontent.com/82084130/118640147-50706580-b7e1-11eb-80ca-11c7e9af2979.png)

from sysdig (which is what I used to test the kernel module):
![image](https://user-images.githubusercontent.com/82084130/118640432-a218f000-b7e1-11eb-9006-c983f028f469.png)

how to recreate:
  in terminal: sysdig "proc.name=xwd and evt.type=connect"
  in another terminal: xwd -out screenshot.img

from what I searched in the code-base, I think this can be handled in https://github.com/falcosecurity/libs/blob/3864a3d3b40dcd39805c38b99ff00ddb2770b1f0/driver/ppm_events.c#L977
with something like
```
if (usrsockaddr_un->sun_path[0] == 0) {
    dest = strncpy(targetbuf + 1, usrsockaddr_un->sun_path + 1, UNIX_PATH_MAX);
}
```

**Comment by FedeDP** [comment]
Hi @HybridReaverHD ! 
Sorry for the very late response; I opened a PR to fix this issue; it will hopefully land soon :) 
Thanks for your patience!
