### ISSUE TITLE
Inconsistent scap values when receiving NULL strings in kmod and ebpf [(NULL)/<NA>/0-length]

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/libs#477]
**Describe the bug**

When the kmod or ebpf probe reads a NULL, or otherwise unavailable, string from the kernel it might behave differently, leading to issues in userspace. Apparently:
- The kernel module will send a `(NULL)` string https://github.com/falcosecurity/libs/blob/5373eb1e8364626b5591d961bfbc7794338ec18d/driver/ppm_events.c#L644 
- The ebpf probe will send a `<NA>` string https://github.com/falcosecurity/libs/blob/5373eb1e8364626b5591d961bfbc7794338ec18d/driver/bpf/filler_helpers.h#L835

Userspace only handles `(NULL)` and not `<NA>`, and due to potential TOCTOU issues will favor the entry arguments of a syscall if the parameter exists both in entry and exit, leading to `fd.name` being set to `/<NA>` in case the BPF probe received the name only from the exit event and not from the entry event, which is obviously wrong

I wonder why the driver and bpf probe are sending these bogus strings for NULL arguments. It sounds like it would be cleaner to send an argument with length 0 (which is different from an empty string that would have length 1, only the null terminator) to represent a NULL string instead, but it's not clear (requires investigation) if there are other corner cases that would be impacted by such a change.

**How to reproduce it**

see https://github.com/falcosecurity/falco/issues/2126

**Expected behaviour**

`fd.name` is correctly set to the exit event value.

**Environment**

- Falco version: since 0.31.1
- System info: eBPF probe installation

**Additional context**

**Comment by Andreagit97** [comment]
Thank you @LucaGuerra for pointing this out i will take a look :eyes:
