### ISSUE TITLE
Documentation: libs release branch testing doc (more details) 

### ISSUE THREAD

**Issue by incertum** [falcosecurity/libs#587]
Based on the discussion in https://github.com/falcosecurity/libs/pull/580 additional documentation can help increase technical clarity around additional testing of libs in release branches.

@incertum team up with maintainers to help create v1 of such a doc. https://github.com/falcosecurity/libs/pull/580#discussion_r965072203

CC @leogr @Molter73

**Comment by leogr** [comment]
Assuming this has been fixed by #580 

/close
