### ISSUE TITLE
[FEATURE] Missing syscalls modern BPF probe

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/libs#723]
**Feature**

Right now the modern BPF probe support only a subset of the syscall supported by the current one, the so-called "simple set". You can check here the supported syscalls :point_down: 

https://github.com/falcosecurity/libs/issues/513

**Missing syscalls** = 56

- [x] access 
- [x] brk
- [x] epoll_wait
- [x] fstat
- [x] futex
- [x] getcwd
- [x] getdents
- [x] getdents64
- [x] getegid
- [x] geteuid
- [x] getgid
- [x] getpeername
- [x] getresgid
- [x] getresuid
- [x] getrlimit
- [x] getsockname
- [x] getsockopt
- [x] getuid
- [x] io_uring_enter
- [x] io_uring_register
- [x] io_uring_setup
- [x] llseek
- [x] lseek
- [x] lstat
- [x] mlock
- [x] mlock2
- [x] mlockall
- [x] mmap
- [x] mmap2
- [x] mprotect
- [x] munlock
- [x] munlockall
- [x] munmap
- [x] nanosleep
- [x] poll
- [x] ppoll
- [x] pread64
- [x] preadv
- [x] pwrite64
- [x] pwritev
- [x] read
- [x] readv
- [x] recvmmsg
- [x] select
- [x] semctl
- [x] semget
- [x] semop
- [x] sendfile
- [x] sendmmsg
- [x] splice
- [x] stat 
- [x] ugetrlimit
- [x] write
- [x] writev
- [x] send
- [x] recv

There are some syscalls that should be never compiled unless you compile libs on some particular machines (kernel built without `CONFIG_64BIT`):

- [ ] fcntl64
- [ ] stat64
- [ ] fstat64
- [ ] sendfile64
- [ ] setresuid32
- [ ] setresgid32
- [ ] setuid32
- [ ] setgid32
- [ ] getuid32
- [ ] geteuid32
- [ ] getgid32
- [ ] getegid32
- [ ] getresuid32
- [ ] getresgid32

As you can notice they are all 64/32 bit versions of already implemented syscalls. Let's say that they are low-priority and very easy to implement, we can keep them as a last step to reach full parity :)

We need also to implement the generic one but this should be quite easy to do:
- [x] generic syscall support (https://github.com/falcosecurity/libs/pull/814)

Missing tracepoints:
- [x] page_fault_user
- [x] page_fault_kernel
- [x] signal_deliver

**Comment by Andreagit97** [comment]
I've noticed that we miss other 3 important syscalls that for some reason are never compiled according to our [compact files](https://github.com/falcosecurity/libs/blob/master/driver/syscall_compat_x86_64.h)
-  llseek
- mmap2
- ugetrlimit

**Comment by Andreagit97** [comment]
Moreover, there are some syscalls that should be never compiled unless you compile libs on some particular machines:

- [ ] fcntl64
- [ ] stat64
- [ ] fstat64
- [ ] sendfile64
- [ ] setresuid32
- [ ] setresgid32
- [ ] setuid32
- [ ] setgid32
- [ ] getuid32
- [ ] geteuid32
- [ ] getgid32
- [ ] getegid32
- [ ] getresuid32
- [ ] getresgid32

As you can notice they are all 64/32 bit versions of already implemented syscalls. Let's say that they are low-priority and very easy to implement, we can keep them as a last step to reach full parity :)

**Comment by FedeDP** [comment]
> I've noticed that we miss other 3 important syscalls that for some reason are never compiled according to our [compact files](https://github.com/falcosecurity/libs/blob/master/driver/syscall_compat_x86_64.h)

It seems like they're not present on x86: https://marcin.juszkiewicz.com.pl/download/tables/syscalls.html!

I am not sure how to proceed; they exist on other architectures. In syscalls bumper, i assumed that "x86_64" always had the larges possible set; i think we might have to fix that.

**Comment by Andreagit97** [comment]
yeah, it seems that none of our 3 supported architectures defines them :/

**Comment by Andreagit97** [comment]
Hey all, in the next weeks I will take care of implementing the following syscalls:
- [ ] `writev`
- [ ] `pwrite64`
- [ ] `pwritev`

I post it here so we avoid implementing 2 times same syscalls since now we have different folks from the community working on it (thank you very much @dwindsor @loresuso @hbrueckner :tada: )

**Comment by Andreagit97** [comment]
BTW i would keep this issue open until we will implement also these corner cases :)

**Comment by loresuso** [comment]
Great news! 🥳

**Comment by FedeDP** [comment]
Heroic effort from multiple people! Thank you very much to everyone involved!
Let me thanks Andrea specifically for its huge work on the modern bpf architecture, programs(attached and tail called) and testing framework.
Superb work!

**Comment by Andreagit97** [comment]
Collected the remaining points into #1004 we can close this :) 
/close
