### ISSUE TITLE
sinsp-example run with -m option error

### ISSUE THREAD

**Issue by qcha0** [falcosecurity/libs#756]
**Describe the bug**
```
[root@localhost examples]# sudo ./sinsp-example -m
./sinsp-example: invalid option -- 'm'
```

**How to reproduce it**
built with default branch, run with -m option would reproduce it

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/12856766/204977930-0704c3a4-2c28-4dad-bd34-c8b39b33bde2.png)

**Environment**

**Additional context**

**Comment by Andreagit97** [comment]
yeah, it was a regression from the last release, thank you for fixing it!
