### ISSUE TITLE
Get Falco libraries as shared object(.so)

### ISSUE THREAD

**Issue by liorzemah** [falcosecurity/libs#762]
**Motivation**
I would like to integrate Falcolibs (libsinsp,libscap) with my project and the easier way will be to install your rpm/deb and receive shared objects of your libs (such as: libsinsp.so libscap.so) and then load them in runtime (in this way I can always be apt to date with your repository)

**Feature**

Install shared object via existing rpm/deb 
**Alternatives**

**Additional context**

**Comment by FedeDP** [comment]
Hi @liorzemah !
Do you mean installing Falco and together with it, libsinsp and libscap?
Note that Falco bundles libsinsp and libscap statically; this is to have an executable (Falco) that is as static as possible, so that it can be executed everywhere. For the very same reason, we build Falco (and the libraries within) on a centos7 image, so that glibc used is super old and is supported on every distro.

I think you might instead wish to install libs repo through `make install`. I will tag a couple of friends that i think do exactly that: @terylt @araujof :)

**Comment by terylt** [comment]
Hi @liorzemah and @FedeDP 

We use the libs heavily in our SysFlow project and so have done a lot of work in trying to make them easier to consume.  For example, the `make install` that Federico is talking about puts all the `.a` files and headers into `falcosecurity` directories so it is easier to pull them in together.  We also have in our project, the ability to take falco libs and all it's dependencies and put them into a single big .a file.  We haven't submitted that as a PR yet to falco, but if folks think it's beneficial, we certainly can do so.   It would give you a library like libfalco_with_dep.a, so you don't have to include all 30+ libraries.   This works in most cases, the only time it can cause issues is when your project links to a library that is already in the libfalco_with_deps.a, then there can be symbolic collisions.   

One thing we'd also like to do is somehow encode the version of the libs directly into the library name.  Not sure what the convention for doing this is in static libs.   But having something like libfalco_with_dep_0.10.0.a would help easily differentiate versions.  

Lastly, when we build, we use containers to give us a stable environment to build easily.  For our project, we actually build a library rpm/deb.  We could also help to do this for falco if there is interest.   Makes life easier.  

I find it's easier not to deal with shared objects, especially with the sheer number of dependencies.  You get one lib with no external dependencies.  We actually also compile the libs with MUSL enabled, and that rids us of ANY external dependencies, as MUSL doesn't rely on a glibc or other system libs.

Would also be interested in hearing @geraldcombs opinion, as I know he uses the libs quite extensively in his projects.  @araujof and I are happy to submit back the techniques we've been using for making the libs easier to use if people think it's worth while.  Happy to chat about any of this.

**Comment by terylt** [comment]
One last thing I forgot.  We've also been playing around with a `libs` docker container.  The idea is that you have a docker container that has the libs installed, and it has a couple of environment variables that have all the includes, and libs that are required to build an application from the libs.   With it, users can just use a simple gcc linking command that has the two variables and compile their application.   Every time there is a new version of the libs, you just create a new version of the container and client apps just build based off the latest version when they want to upgrade.

**Comment by geraldcombs** [comment]
> Would also be interested in hearing @geraldcombs opinion, as I know he uses the libs quite extensively in his projects.

Hi @terylt, shared `libs` would be really useful in my case, so I opened #933 to add initial support.

**Comment by terylt** [comment]
@geraldcombs For our project we have a mechanism that can compile all falco libs and dependencies into a single library.  Would that be useful for your use case?  We are thinking about submitting it to the falco project but didn't know if people would find it useful.

**Comment by geraldcombs** [comment]
Hi @terylt, that sounds useful in general but I'm not sure how well it would work in my (possibly unique) case. Logray is more of a traditional application and the build environment assumes that you'll be linking with dynamic libraries provided by your distribution, vcpkg, or Homebrew. I currently have to use minimal `libs` builds, otherwise I run into symbol conflicts from having both static and dynamic versions of zlib.

**Comment by FedeDP** [comment]
I think this is now solved in master:
* We provide pkg config scripts for libs: https://github.com/falcosecurity/libs/pull/546
* we have a CI job that tests the build of libs as shared objects, installs them and then uses the installed pkgconfig scripts to compile an executable

To enable the shared objects build you need to enable the cmake option BUILD_SHARED_LIBS.

**Comment by dkogan** [comment]
These libraries are in stock Debian (and therefore it's in all the derivatives as well). You can `apt install libfalcosecurity0-dev`. What else is required?

**Comment by FedeDP** [comment]
I think this can be closed!
/close

**Comment by geraldcombs** [comment]
Should we pull in the patches at https://salsa.debian.org/debian/falcosecurity-libs/-/tree/master/debian/patches? `fix-library-install-path.patch` looks like a more correct version of #1101 for example.
