### ISSUE TITLE
run sinsp-example with kmod error

### ISSUE THREAD

**Issue by qcha0** [falcosecurity/libs#774]
**Describe the bug**
```
[root@localhost examples]# ./sinsp-example -k -j
-- Try to open: 'kmod' engine.
terminate called after throwing an instance of 'scap_open_exception'
  what():  error opening device /dev/scap0. Make sure you have root credentials and that the scap module is loaded: No such file or directory
Aborted (core dumped)
```

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:
`Rocky Linux release 9.0 (Blue Onyx)`

- Kernel:
`Linux localhost.localdomain 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

- Installation method:
refer [Build](https://github.com/falcosecurity/libs#build)

**Additional context**

**Comment by qcha0** [comment]
I try search like `linux scap module`, `linux /dev/scap` but there is no useful info.

can someone help me.

**Comment by FedeDP** [comment]
Hi! Thanks for taking the time to report this issue!
Did you build kmod? ie: `make driver`? Did you insmod the driver (ie: `insmod driver/scap.ko`)?

**Comment by FedeDP** [comment]
Also, we should really add the logic to auto-start the kmod in sinsp-example when it is not present, just like Falco does.

**Comment by qcha0** [comment]
my fault, I found the `scap.ko` under driver directory，after `insmod scap.ko` i could run successfully.
