### ISSUE TITLE
[FEATURE] Extend glob functionality to allow for lists

### ISSUE THREAD

**Issue by mikescholl-sysdig** [falcosecurity/libs#947]
**Motivation**

Attempting to do FIM checks against lists of directories/files unfortunately does not work today without explicit definition of these files within a rule rather than a re-referenced `list` type. Some of these directories may live in different locations and we want to do multiple checks against a list such as `[/some/*/dir, /another/dir, /some/other/*/dir]`

**Feature**

The `glob` functionality should be able to accept a singular value as well as reference a `list` type to allow for multiple entries within a rule.

**Alternatives**

Looking to add additional logic in the rules today as a workaround to do `pmatch` on prefixes but also `glob` match conditions.

**Additional context**

**Comment by incertum** [comment]
Hi @mikescholl-sysdig this seems related to proposed extensions to the expression language here https://github.com/falcosecurity/falco/issues/2403. We are planning it for Falco 0.36.

**Comment by mikescholl-sysdig** [comment]
hey @incertum the related link notes `contains` specifically; does the improvement extend to the `glob` operator as well?

**Comment by incertum** [comment]
Hi Mike, we should try supporting all operators that make sense including `glob`.
We haven't started looking into possible implementation details, please share your ideas :)

**Comment by jasondellaluce** [comment]
Any way this links to https://github.com/falcosecurity/libs/pull/1091? cc @mstemm

**Comment by mikescholl-sysdig** [comment]
I believe this does handle the use case. I can confirm with additional testing again.

**Comment by mikescholl-sysdig** [comment]
confirmed; can close.
