### ISSUE TITLE
Improve memory leak and memory error detection coverage in CI/testing

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/libs#979]
**Motivation**

It is relatively easy to introduce potential memory leaks and, double frees or possible memory errors in codebases written in C/C++ and occasionally we find some in our codebase (see: https://github.com/falcosecurity/libs/security/advisories/GHSA-c957-pmc3-99qj ). While we do have a code review process in place to catch as many as we can, every automated help is welcome.

**Feature**

I would propose to extend the coverage of sanitizers (AddressSanitizer + LeakSanitizer) to more tests than the unit ones that we're using today. I believe a good candidate for this are the e2e tests that run in CI with libs (already working on making that work, still wip: https://github.com/falcosecurity/libs/pull/978 )

I've opened this issue to gather feedback on other potential ways to catch some of these issues. ( cc @Molter73 )

**Comment by Molter73** [comment]
This is cool! More memory safety is always a good thing!

I would also add UndefinedBehaviorSanitizer to the list, as it can be used with asan and should help catch even more problems.

On a separate note that might even warrant another issue, have we considered adding a CI step using `scan-build`? In my experience, it's not the end all be all static analyzer, but it should be relatively straight forward to set up and it does catch interesting stuff every now and then.

**Comment by Andreagit97** [comment]
what do we miss here? @LucaGuerra

**Comment by LucaGuerra** [comment]
I believe we have implemented what I described in the original issue. In fact, I've seen bugs caught early because of that <3

We can always improve the state of memory error detection but when we, for example, decide to add UBSan support we can open a separate issue. Thanks! :)
