### ISSUE TITLE
[New Feature] Standard logging in Plugin API

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/libs#989]
**Motivation**

In the past, I opened an issue in the Plugin SDK Go (https://github.com/falcosecurity/plugin-sdk-go/issues/24) reporting that current plugin have no way to log messages in a standard way. Thinking about it twice, this should not just involve plugins written in Go with out SDK, but should be something supported by the plugin API in general.

**Feature**

Support new API symbols in the plugin API for letting plugins log messages with a given severity system. On the libraries side, we should leverage the current logging system already implemented inside libsinsp. The top priority non-functional requisite for the feature is to optimize it for performance, as logging can during in paths.

**Additional context**

Linked issues:
- https://github.com/falcosecurity/plugin-sdk-go/issues/24
- https://github.com/falcosecurity/libs/issues/125 (not strict relation, but logging can help with the issue)

**Comment by jasondellaluce** [comment]
This is a good first feature to start contributing to the code area related to the plugin system. Is anyone interested?

Setting a milestone for visibility, we can move this issue to the next one in case we think it's not feasible.

/milestone 0.11.0

**Comment by Andreagit97** [comment]
Not sure we can do this for libs 0.12.0. It is possible we will move this to 0.13.0
